model_id: "BAAI/bge-large-en-v1.5"
spacy_model: "en_core_web_sm"
top_k: 10
pdf_dir: "folder_pdf/"

user_skill_weight: 0.8
user_experience_weight: 0.2

target_jd_similarity: 0.8
target_skills: 8
target_months_base: 60          # we'll multiply this by user_experience_weight in code
target_word_count: 400
target_gpa: 3.2

weight_jd: 30
weight_skill: 50
weight_months: 50
weight_word: 10
weight_gpa: 10

fuzzy_title_match_threshold: 70
fuzzy_skill_match_threshold: 85